{% set name = "openff-recharge" %}
{% set version = "0.0.1a7" %}
{% set sha256 = "944ce1013c4027edac7197be23581ba98c2180ed5bb35d57b04bd2887eb4ff6e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version | replace("a", "-alpha.") }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - tqdm
    - cmiles-base
    - numpy
    - pydantic
    - jinja2
    - sqlalchemy
    - sqlite
    - typing-extensions

test:
  imports:
    - openff.recharge

about:
  home: https://github.com/openforcefield/openff-recharge
  license: MIT
  license_file: LICENSE
  description: An automated framework for generating optimized partial charges for molecules.

extra:
  recipe-maintainers:
    - simonboothroyd