{% set name = "openff-recharge" %}
{% set version = "0.0.1a2" %}
{% set sha256 = "8a6fbba1527edf5ce6d79b7f8326a6ea9143a9130b8913d92b942ff0bb761c80" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/{{ name }}/archive/{{ version | replace("a", "-alpha.") }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - numpy
    - pydantic
    - jinja2
    - sqlalchemy
    - sqlite
    - typing-extensions

test:
  imports:
    - openff.recharge

about:
  home: https://github.com/openforcefield/openff-recharge
  license: MIT
  license_file: LICENSE
  description: An automated framework for generating optimized partial charges for molecules.

extra:
  recipe-maintainers:
    - simonboothroyd